apiVersion: v1
kind: Namespace
metadata:
  name: lab-infra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ministack
  namespace: lab-infra
  labels:
    app: ministack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ministack
  template:
    metadata:
      labels:
        app: ministack
    spec:
      containers:
        - name: ministack
          image: ministackorg/ministack:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway
              containerPort: 4566
          env:
            - name: GATEWAY_PORT
              value: "4566"
            - name: LOG_LEVEL
              value: "INFO"
            - name: USE_SSL
              value: "0"
            - name: AWS_DEFAULT_REGION
              value: "ap-south-1"
            - name: DEFAULT_REGION
              value: "ap-south-1"
          livenessProbe:
            httpGet:
              path: /_ministack/health
              port: 4566
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /_ministack/health
              port: 4566
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ministack-svc
  namespace: lab-infra
  labels:
    app: ministack
spec:
  type: NodePort
  selector:
    app: ministack
  ports:
    - name: gateway
      port: 4566
      targetPort: 4566
      nodePort: 31566
      protocol: TCP
